### PR TITLE
Hopefully fix taint issues

### PR DESCRIPTION
**Pull request by Shauren**
Maybe, just maybe it fixes it

This is very likely to change filtering behavior  - whatever default blizzard map filters does is no longer removed

Personally I don't use filters so I didn't look at that part

### CODE REVIEW

**Comment by ynazar1** [comment]
Why not create from mixins which creates a local copy?

**Comment by ynazar1** [comment]
Spitballing on code, could this work?

```
local pin =  CreateFromMixins(POIButtonMixin)
```

**Comment by Shauren** [comment]
No, `pin` here is a existing blizzard map world quest pin, it is not created by this addon

Perhaps `POIButtonMixin.OnEnter(pin)` should have been `pin:OnEnter()` but that doesn't make a huge difference here

**Comment by ynazar1** [comment]
> No, `pin` here is a existing blizzard map world quest pin, it is not created by this addon

Hmmm. A dangerous double-edged sword here if and when anything changes with blizzard pins.

**Comment by ynazar1** [comment]
Issue: The pins are not popping up on the continent map

**Comment by Shauren** [comment]
Yeah, doesn't work with AWQ alone, worked with a bunch of other addons I had enabled

**Comment by Shauren** [comment]
Actually... I'm not seeing taint errors on PTR with this (but pins not showing up on continent map is broken by this change)

**Pull request closed without merging**
